### PR TITLE
Updated dependency checker, related to PR #114

### PR DESCRIPTION
**Pull request by razman786**
In-line with comments from PR https://github.com/ska-sa/tigger/pull/114 the dependency checker has been updated to show which dependencies are missing and provides a GUI interface (dependencies allowing).

### CODE REVIEW

**Comment by Athanaseus** [comment]
I get:
```
$ tigger                                                          
Traceback (most recent call last):                                                                       
  File "/home/athanaseus/.local/bin/tigger", line 7, in <module>                                         
    exec(compile(f.read(), __file__, 'exec'))                                                            
  File "/home/athanaseus/KERN/tigger/TigGUI/tigger", line 23, in <module>  
    import Tools.dependency_check  # checks dependencies are available            
ModuleNotFoundError: No module named 'Tools'
```

and fixed it with
```
-import Tools.dependency_check  # checks dependencies are available
+from TigGUI.Tools import dependency_check  # checks dependencies are available
```
Screenshot from 2021-07-20 09-37-15

**Comment by razman786** [comment]
My bad, my ENV in PyCharm must be wonky. Glad it's working for you now though 🙂

**Review by Athanaseus — APPROVED** [review]
Looks Good

**Comment by bennahugo** [comment]
ok to test

**Comment by bennahugo** [comment]
I don't have powers to merge these. Can @o-smirnov please merge

**Pull request merged**
