### PR TITLE
Prepare release 160

### PR DESCRIPTION
**Pull request by Athanaseus**
- Add github-actions to test installation and deployement.

### CODE REVIEW

**Comment by razman786** [comment]
The test environment might need `export PATH=${PATH}:~/.local/bin` to be set?

**Comment by Athanaseus** [comment]
ok i just set that. But I see `==== Installer fullstack mode - astro-tigger-lsm not found... ====`.
manual installation did work though.

**Comment by razman786** [comment]
So this output `==== Installer fullstack mode - astro-tigger-lsm not found... ====` means that it did not find tigger-lsm installed when checking pip. Therefore, it will install tigger-lsm as it is a dependency for tigger. `fullstack` mode simply means install tigger-lsm as well as tigger. 

I can see from the CI build that it outputs `==== Installing Tigger-LSM dependency from pip3... ====` afterwards. It would be useful to see what the tigger_installer.log and tigger_installer.err files show?

**Comment by razman786** [comment]
@Athanaseus - Ok so I did a bit quick of digging. If the test script runs `sudo ./install_tigger_ubuntu.sh` then tigger is installed into `/root/.local/bin`. 

Running the install script with `sudo` should not be needed as it will call `sudo` when needed. If you omit `sudo` then tigger is installed into `/home/runner/.local/bin`.

Adding `$HOME/.local/bin/tigger` to the Test Command section then removes the tigger command not found error. However, I note that the following error occurs instead:
```python
Run $HOME/.local/bin/tigger 
Traceback (most recent call last):
  File "/home/runner/.local/bin/tigger", line 4, in <module>
    __import__('pkg_resources').run_script('astro-tigger==1.6.0', 'tigger')
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/home/runner/.local/lib/python3.8/site-packages/astro_tigger-1.6.0-py3.8.egg/EGG-INFO/scripts/tigger", line 24, in <module>
    from PyQt5.QtCore import Qt
ModuleNotFoundError: No module named 'PyQt5'
Error: Process completed with exit code 1.
```

**Comment by Athanaseus** [comment]
@razman786 am I missing something? Now I get the `ModuleNotFoundError: No module named 'PyQt5'` on the test env.

**Comment by razman786** [comment]
Ummm... the install script installs the following via apt for PyQt5 automatically (amongst other things):

`python3-pyqt5 python3-pyqt5.qtsvg python3-pyqt5.qtopengl`

I'm not sure if GitHub actions does something strange when using `apt install`, or simply that they are not on the PYTHON_PATH (or equiv.) automatically? 

Normally, once the PyQt5 Debian package is installed it should be present here `/usr/lib/python3/dist-packages/PyQt5` and be listed with pip, i.e. `pip3 list|grep PyQt5`. Do you know if that holds true for Github Actions?

**Comment by razman786** [comment]
@Athanaseus - I found the issue (https://github.com/actions/setup-python/issues/178) and is pretty much what I thought from my previous comment. I have a working version and will send a PR to this branch later tonight.

**Comment by razman786** [comment]
@Athanaseus - I've added the PR with the working test builds here https://github.com/ska-sa/tigger/pull/114

**Comment by Athanaseus** [comment]
Thanks @razman786 I see it now.

**Comment by Athanaseus** [comment]
resolved by #114

**Pull request closed without merging**
