### PR TITLE
Define f0 outside the "if" block

### PR DESCRIPTION
**Pull request by SpheMakh**

### CODE REVIEW

**Comment by SpheMakh** [comment]
**Defcon 1 Fix**

Master cannot use ASCII sky models as things stand.
```
0.6Gb lsmformats(ASCII.py:362:load): test.txt:2: local variable 'f0' referenced before assignment, skipping
```

**Comment by o-smirnov** [comment]
Was this broken by #84? @sjperkins could you please have a quick look?

**Comment by SpheMakh** [comment]
@o-smirnov yup. The 'f0' variable is defined in an 'if' block, then used further down.

**Comment by sjperkins** [comment]
Yep, this fix looks correct

**Pull request merged**
